server:
  port: 8081

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET:ride-challenge-jwt-secret-key-32-bytes-minimum-value}
    expiration-seconds: 86400

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5433/account_db
    username: rideapp
    password: rideapp123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
