server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/account_db
    username: rideapp
    password: rideapp123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
